# This Makefile was generated by Nix.
# To make changes edit the `tasks.nix` file.

main: task-help

task-help:
	@echo "usage: make <task>"
	@echo ""
	@echo "Available Tasks:"
	@echo -e '	gen-readme'
	@echo -e "\nUse 'make task-help' command to show this list."
	

gen-readme: 
	./txtx.py README.mdx > README.md
	
